// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiCareSys.Data.Models;

[Table("development_stage")]
public partial class DevelopmentStage
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Column("stage_name")]
    public string StageName { get; set; }

    [Column("required_food_amount")]
    public decimal? RequiredFoodAmount { get; set; }

    [InverseProperty("DevelopmentStage")]
    public virtual ICollection<KoiRecord> KoiRecords { get; set; } = new List<KoiRecord>();

}