// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiCareSys.Data.Models;

[Table("feeding_schedule")]
public partial class FeedingSchedule
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Column("foodcaculate")]
    public decimal? Foodcaculate { get; set; }

    [Column("feed_at")]
    public DateTime FeedAt { get; set; }

    [Column("food_amount")]
    public decimal? FoodAmount { get; set; }

    [Column("feed_by")]
    public string? FeedBy { get; set; }

    [Column("temperature")]
    public decimal? Temperature { get; set; }

    [Column("food_type")]
    public string? FoodType { get; set; }

    [Column("note")]
    public string? Note { get; set; }

    [Column("pond_id")]
    [ForeignKey("Pond")]
    public Guid PondId { get; set; }
    public virtual Pond Pond { get; set; }
}