// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiCareSys.Data.Models;

[Table("koi")]
public partial class Koi
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Column("name")]
    [Required]
    public string Name { get; set; }

    [Column("physique")]
    [Required]
    public string Physique { get; set; }

    [Column("age")]
    [Required]
    public int? Age { get; set; }

    [Column("length")]
    [Required]
    public decimal? Length { get; set; }

    [Column("Sex")]
    [EnumDataType(typeof(Enums.KoiSex))]
    public Enums.KoiSex Sex { get; set; } = Enums.KoiSex.Unknown;

    [Column("category")]
    public string Category { get; set; }

    [Column("in_pond_since")]
    [Required]
    public DateOnly? InPondSince { get; set; }
    [Column("purchase_price")]
    public decimal? PurchasePrice { get; set; }

    [Column("status")]
    [EnumDataType(typeof(Enums.KoiStatus))]
    public Enums.KoiStatus Status { get; set; } = Enums.KoiStatus.Active;

    [Column("img_url")]
    [Url]
    public string ImgUrl { get; set; }

    [Column("origin")]
    public string Origin { get; set; }

    [Column("breed")]
    public string Breed { get; set; }

    [Column("pond_id")]
    [ForeignKey("Pond")]
    public Guid PondId { get; set; }
    public virtual Pond Pond { get; set; } = null;

    [InverseProperty("Koi")]
    public ICollection<KoiRecord> KoiRecords { get; set; } = new List<KoiRecord>();

    [InverseProperty("Koi")]
    public ICollection<FeedingSchedule> FeedingSchedules { get; set; } = new List<FeedingSchedule>();

}