// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace KoiCareSys.Data.Models;

[Table("measure_data")]
public partial class MeasureData
{
    [Key]
    [Column("id")]
    public Guid MeasureDataId { get; set; } = Guid.NewGuid();

    [Column("volume")]
    public decimal? Volume { get; set; }

    [Column("measurement_id")]
    [ForeignKey("Measurement")]
    public Guid MeasurementId { get; set; }
    [JsonIgnore]
    public virtual Measurement Measurement { get; set; }

    [Column("unit_id")]
    [ForeignKey("Unit")]
    public Guid UnitId { get; set; }
    public virtual Unit Unit { get; set; }
}