// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiCareSys.Data.Models;

[Table("measurement")]
public partial class Measurement
{
    [Key]
    [Column("measurement_id")]
    public Guid MeasurementId { get; set; } = Guid.NewGuid();

    [Column("date_record")]
    public DateTime DateRecord { get; set; }

    [Column("note")]
    public string? Note { get; set; }

    [Column("pond_id")]
    [ForeignKey("Pond")]
    public Guid PondId { get; set; }
    public virtual Pond Pond { get; set; }

    [InverseProperty("Measurement")]
    public virtual ICollection<MeasureData> MeasureData { get; set; } = new List<MeasureData>();


}