// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiCareSys.Data.Models;

[Table("pond")]
public partial class Pond
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Column("pond_name")]
    [Required]
    public string PondName { get; set; }

    [Column("volume")]
    [Required]
    public decimal? Volume { get; set; }

    [Column("depth")]
    [Required]
    public decimal? Depth { get; set; }

    [Column("drain_count")]
    public int? DrainCount { get; set; }

    [Column("skimmer_count")]
    public int? SkimmerCount { get; set; }

    [Column("pump_capacity")]
    public decimal? PumpCapacity { get; set; }

    [Column("img_url")]
    [Url]
    public string ImgUrl { get; set; }
    
    [Column("note")]
    public string Note { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("status")]
    [EnumDataType(typeof(Enums.PondStatus))]
    public Enums.PondStatus Status { get; set; }

    [Column("is_qualified")]
    public bool? IsQualified { get; set; }

    [Column("user_id")]
    [ForeignKey("User")]
    public Guid UserId { get; set; }
    public virtual User User { get; set; } = null;

    [InverseProperty("Pond")]
    public ICollection<Koi> Koi { get; set; } = new List<Koi>();

    [InverseProperty("Pond")]
    public ICollection<Measurement> Measurements { get; set; } = new List<Measurement>();

    [InverseProperty("Pond")]
    public ICollection<FeedingSchedule> FeedingSchedules { get; set; } = new List<FeedingSchedule>();
}