// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiCareSys.Data.Models;

[Table("unit")]
public partial class Unit
{
    [Key]
    [Column("id")]
    public Guid UnitId { get; set; } = Guid.NewGuid();

    [Column("name")]
    public string Name { get; set; }

    [Column("unit_of_measure")]
    public string UnitOfMeasure { get; set; }

    [Column("full_name")]
    public string FullName { get; set; }

    [Column("information")]
    public string Information { get; set; }

    [Column("min_value")]
    public decimal? MinValue { get; set; }

    [Column("max_value")]
    public decimal? MaxValue { get; set; }

    [InverseProperty("Unit")]
    public virtual ICollection<MeasureData> MeasureData { get; set; } = new List<MeasureData>();
}